//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrineFoxCom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShrineFoxCom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;column col-6 col-sm-12&quot;&gt;
        ///    &lt;div class=&quot;card&quot;&gt;
        ///        &lt;div class=&quot;card-image&quot;&gt;
        ///            &lt;img class=&quot;img-responsive&quot; src=&quot;CARDIMGSOURCE&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-header&quot;&gt;
        ///            &lt;div class=&quot;card-title h5&quot;&gt;
        ///                CARDTITLE
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;card-subtitle text-muted&quot;&gt;
        ///               CARDSUBTITLE
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-body&quot;&gt;
        ///            CARDBODY
        ///        &lt;/div&gt;
        ///        &lt;br&gt;
        ///        &lt;div  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///--------------------------------------------------------------
        ///Colours and backgrounds for common.css
        ///-------------------------------------------------------------- */
        ///
        ///html, body {
        ///	color: rgba(0,0,0,.4);
        ///	background-color: #ECF0F1;
        ///}
        ///
        ///body {
        ///	background-color: transparent; /* Required for parallax */
        ///}
        ///
        ///h1 {
        ///	color: #FFFFFF;
        ///}
        ///
        ///h2 {
        ///	color: #28313F;
        ///}
        ///
        ///h3 {
        ///	border-bottom-color: #CCCCCC;
        ///}
        ///
        ///hr {
        ///	border-color: #FFFFFF;
        ///	border-top-color: #CCCCCC;
        ///}
        ///
        ////*
        ///------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colours {
            get {
                return ResourceManager.GetString("colours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bloody11
        ///Juza64.
        /// </summary>
        internal static string exclude {
            get {
                return ResourceManager.GetString("exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The template for displaying the footer.
        /// *
        /// * Contains the closing of the #content div and all content after.
        /// *
        /// * @link https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#footer-php
        /// *
        /// * @package Primer
        /// * @since   1.0.0
        /// */
        ///
        ///?&gt;
        ///
        ///		&lt;/div&gt;&lt;!-- #content --&gt;
        ///
        ///
        ///	&lt;/div&gt;&lt;!-- #page --&gt;
        ///
        ///	&lt;!--ShrineFox Footer--&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The template for displaying the header.
        /// *
        /// * Displays all of the head element and everything up until the &quot;site-content&quot; div.
        /// *
        /// * @package Primer
        /// * @since   1.0.0
        /// */
        ///
        ///?&gt;&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html &lt;?php language_attributes(); ?&gt;&gt;
        ///
        ///&lt;head&gt;
        ///	
        ///	&lt;meta charset=&quot;&lt;?php bloginfo( &apos;charset&apos; ); ?&gt;&quot;&gt;
        ///
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///
        ///	&lt;link rel=&quot;profile&quot; href=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///
        ///	&lt;link rel=&quot;pingback&quot; href=&quot;&lt;?php bloginfo( &apos;pingback_url&apos; );  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///    &lt;!--ShrineFox NavBar--&gt;
        ///    &lt;header&gt;
        ///        &lt;section class=&quot;navbar-section desktop-menu&quot;&gt;
        ///            &lt;nav class=&quot;navbar dropmenu animated navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3&quot;&gt;
        ///                &lt;div class=&quot;container accent&quot;&gt;
        ///                    &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot; onclick=&quot;window.location.reload(true);&quot;&gt;
        ///                        &lt;!--Logo--&gt;
        ///                        &lt;svg version=&quot;1.0&quot; class=&quot;amicitialogo&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_body {
            get {
                return ResourceManager.GetString("home_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/main&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;!--ShrineFox Footer--&gt;
        ///&lt;footer class=&quot;footer text-muted&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;div class=&quot;columns&quot;&gt;
        ///            &lt;div class=&quot;column col-6&quot;&gt;
        ///                &amp;copy; ShrineFox 2020 - 2022
        ///                &lt;script&gt;
        ///                    document.addEventListener(&quot;DOMContentLoaded&quot;, function (event) {
        ///                        var controller = new YTV(&apos;YourPlayerID&apos;, {
        ///                            channelId: &apos;UCrB3t1zAQPwAeWtI8RZIOvQ&apos;,
        ///                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_foot {
            get {
                return ResourceManager.GetString("home_foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;ShrineFox.com&lt;/title&gt;
        ///    &lt;!--ShrineFox AllStyles--&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/bootstrap.min.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/spectre.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/spectre-icons.css&quot; /&gt;
        ///    &lt;!--ShrineFox Styles--&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_head {
            get {
                return ResourceManager.GetString("home_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg version=&quot;1.0&quot; class=&quot;amicitialogo&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;
        /// width=&quot;500.000000pt&quot; height=&quot;500.000000pt&quot; viewBox=&quot;0 0 500.000000 500.000000&quot;
        /// preserveAspectRatio=&quot;xMidYMid meet&quot;&gt;
        ///  &lt;metadata&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;g transform=&quot;translate(0.000000,500.000000) scale(0.100000,-0.100000)&quot;
        ///  fill=&quot;#ffffff&quot; stroke=&quot;none&quot;&gt;
        ///    &lt;path d=&quot;M2256 4489 c-926 -119 -1651 -850 -1766 -1779 -15 -125 -12 -405 5
        ///-529 65 -450 258 -836 579 -1157 67 -66 164 -152 216 -191 136 -100 310 -203
        ///343 -203 14 0 48 114 141 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					&lt;!-- IF STYLE_SETTINGS_CONFIG_SIDEBARS --&gt;
        ///                            		&lt;/div&gt;
        ///                                &lt;/div&gt;
        ///                            &lt;/div&gt;
        ///
        ///							&lt;!-- IF STYLE_SETTINGS_CONFIG_SIDEBAR_PLACEMENT == &apos;Left Only&apos; || STYLE_SETTINGS_CONFIG_SIDEBAR_PLACEMENT == &apos;Both&apos; --&gt;
        ///                            &lt;div id=&quot;leftcolumn&quot;&gt;
        ///                            	&lt;div class=&quot;innertube&quot;&gt;&lt;!-- INCLUDE sidebar_left.html --&gt;&lt;/div&gt;
        ///                            &lt;/div&gt;
        ///                            &lt;!-- ENDIF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_footer {
            get {
                return ResourceManager.GetString("overall_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;{S_CONTENT_DIRECTION}&quot; lang=&quot;{S_USER_LANG}&quot;&gt;
        ///&lt;head&gt;
        ///{% if STYLE_SETTINGS_CONFIG_ALLOW_USER_COLOUR %}	
        ///	&lt;script&gt; if (localStorage.user_colour_selection === &quot;dark&quot;) { document.getElementsByTagName(&apos;html&apos;)[0].classList.add(&apos;fd_dark&apos;); }&lt;/script&gt;	
        ///{% endif %}
        ///	&lt;!--ShrineFox Styles--&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///{META}
        ///&lt;title&gt;&lt;!-- IF UNREAD_NOTIFICATIONS_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_header {
            get {
                return ResourceManager.GetString("overall_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Expand executable memory size (default: 0x9ACC80)
        ///patch=0,EE,0077F494,word,0xAACC80
        ///
        ///// Jump to loader entrypoint at 0x009ACC80
        ///patch=0,EE,00193980,word,0826B320
        ///patch=0,EE,00193984,word,00000000
        ///
        ///// &lt;PnachPatchGen:start&gt;
        ///patch=0,EE,009ACC80,word,00000000
        ///patch=0,EE,009ACC84,word,00000000
        ///patch=0,EE,009ACC88,word,00000000
        ///patch=0,EE,009ACC8C,word,00000000
        ///patch=0,EE,009ACC90,word,00000000
        ///patch=0,EE,009ACC94,word,00000000
        ///patch=0,EE,009ACC98,word,00000000
        ///patch=0,EE,009ACC9C,word,00000000        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P3FES_hostFS {
            get {
                return ResourceManager.GetString("P3FES_hostFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Expand executable memory size (default: 0x938A00)
        ///patch=0,EE,0070C5D4,word,0xA38A00
        ///
        ///// Jump to loader entrypoint at 0x938A00
        ///patch=0,EE,001002C0,word,0824E280
        ///patch=0,EE,001002C4,word,00000000
        ///
        ///// &lt;PnachPatchGen:start&gt;
        ///patch=0,EE,00938A00,word,27BDFE00
        ///patch=0,EE,00938A04,word,FFBF0110
        ///patch=0,EE,00938A08,word,0C24E29F
        ///patch=0,EE,00938A0C,word,00000000
        ///patch=0,EE,00938A10,word,3C010094
        ///patch=0,EE,00938A14,word,24218F00
        ///patch=0,EE,00938A18,word,FC3C0000
        ///patch=0,EE,00938A1C,word,3C1C0095
        ///p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P4_hostFS {
            get {
                return ResourceManager.GetString("P4_hostFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P5R PS4 USA	0505+intro_skip+p5_save+share_button+square+mod	EBOOT	http://up-4.net/d/V3pL
        ///P5R PS4 USA	0505+intro_skip+p5_save+share_button+square+mod	PKG	http://up-4.net/d/V3qS
        ///P5R PS4 USA	0505+intro_skip+p5_save+share_button+square+mod+dlc	EBOOT	http://up-4.net/d/V3s6
        ///P5R PS4 USA	0505+intro_skip+p5_save+share_button+square+mod+dlc	PKG	http://up-4.net/d/V3uK
        ///P5R PS4 USA	0505+intro_skip+p5_save+share_button+square+mod+dlc+bgm_ord	EBOOT	http://up-4.net/d/V3zB
        ///P5R PS4 USA	0505+intro_skip+p5_save+share_butt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string patch_downloads {
            get {
                return ResourceManager.GetString("patch_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;column col-4 col-sm-12&quot;&gt;
        ///    &lt;div class=&quot;card&quot;&gt;
        ///        &lt;div class=&quot;card-image&quot;&gt;
        ///            &lt;img class=&quot;img-responsive&quot; src=&quot;POSTMEDIAURL&quot;&gt;
        ///            &lt;div class=&quot;yt-overlay&quot; style=&quot;display:none&quot;&gt;&lt;a href=&quot;EMBEDURL&quot;&gt;&lt;i class=&quot;fas fa-play-circle&quot;&gt;&lt;/i&gt;&lt;/div&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-header&quot;&gt;
        ///            &lt;div class=&quot;card-title h5&quot;&gt;
        ///                POSTID POSTTITLE
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;card-subtitle text-muted&quot;&gt;
        ///                GAMEBANANA POSTTYPE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Theme Name: Primer
        /// * Theme URI: https://github.com/godaddy/wp-primer-theme
        /// * Author: GoDaddy
        /// * Author URI: https://www.godaddy.com/
        /// * Description: Primer is a powerful theme that brings clarity to your content in a fresh design.
        /// * Version: 1.8.9
        /// * License: GPL-2.0
        /// * License URI: https://www.gnu.org/licenses/gpl-2.0.html
        /// * Text Domain: primer
        /// * Domain Path: /languages
        /// * Tags: custom-background, custom-colors, custom-header, custom-menu, editor-style, featured-images, flexible-head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
