//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrineFoxCom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShrineFoxCom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;column col-6 col-sm-12&quot;&gt;
        ///    &lt;div class=&quot;card&quot;&gt;
        ///        &lt;div class=&quot;card-image&quot;&gt;
        ///            &lt;img class=&quot;img-responsive&quot; src=&quot;CARDIMGSOURCE&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-header&quot;&gt;
        ///            &lt;div class=&quot;card-title h5&quot;&gt;
        ///                CARDTITLE
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;card-subtitle text-muted&quot;&gt;
        ///               CARDSUBTITLE
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-body&quot;&gt;
        ///            CARDBODY
        ///        &lt;/div&gt;
        ///        &lt;br&gt;
        ///        &lt;div class=&quot;card-foote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///--------------------------------------------------------------
        ///Colours and backgrounds for common.css
        ///-------------------------------------------------------------- */
        ///
        ///html, body {
        ///    color: var(--pagetext);
        ///    background-color: var(--postbackground);
        ///}
        ///
        ///h1 {
        ///	color: rgba(var(--text),0.05);
        ///}
        ///
        ///h2 {
        ///	color: var(--pageheading);
        ///}
        ///
        ///h3 {
        ///	border-bottom-color: var(--pageheading);
        ///	color: var(--pageheading);
        ///}
        ///
        ///hr {
        ///	border-color: rgba(var(--text),0.05);
        ///	border-top-color: var(--pageheading);
        ///}
        ///
        ///.search-box [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colours {
            get {
                return ResourceManager.GetString("colours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bloody11.
        /// </summary>
        internal static string exclude {
            get {
                return ResourceManager.GetString("exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The template for displaying the footer
        /// *
        /// * Contains the closing of the #content div and all content after.
        /// *
        /// * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
        /// *
        /// * @package Justread
        /// */
        ///
        ///?&gt;
        ///
        ///	&lt;/div&gt;&lt;!-- #content --&gt;
        ///			&lt;!--INDEXFOOTER--&gt;.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The header for our theme
        /// *
        /// * This is the template that displays all of the &lt;head&gt; section and everything up until &lt;div id=&quot;content&quot;&gt;
        /// *
        /// * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
        /// *
        /// * @package Justread
        /// */
        ///
        ///?&gt;
        ///&lt;!doctype html&gt;
        ///&lt;html class=&quot;no-js&quot; &lt;?php language_attributes(); ?&gt;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;&lt;?php bloginfo( &apos;charset&apos; ); ?&gt;&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;link rel=&quot;profile&quot; href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///    &lt;header&gt;
        ///        &lt;section class=&quot;navbar-section desktop-menu&quot;&gt;
        ///            &lt;nav class=&quot;navbar dropmenu animated navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3&quot;&gt;
        ///                &lt;div class=&quot;container accent&quot;&gt;
        ///                    &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot; onclick=&quot;window.location.reload(true);&quot;&gt;
        ///                        &lt;!--Logo--&gt;
        ///                        &lt;svg version=&quot;1.0&quot; class=&quot;amicitialogo&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                             width= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_body {
            get {
                return ResourceManager.GetString("home_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/main&gt;
        ///&lt;/div&gt;
        ///&lt;!-- Footer --&gt;
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;footer class=&quot;footer text-muted&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;div class=&quot;columns&quot;&gt;
        ///            &lt;div class=&quot;column col-6&quot;&gt;
        ///                &amp;copy; ShrineFox 2020 - 2021
        ///                &lt;script&gt;
        ///                    document.addEventListener(&quot;DOMContentLoaded&quot;, function (event) {
        ///                        var controller = new YTV(&apos;YourPlayerID&apos;, {
        ///                            channelId: &apos;UCrB3t1zAQPwAeWtI8RZIOvQ&apos;,
        ///                            play [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_foot {
            get {
                return ResourceManager.GetString("home_foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;ShrineFox.com&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/bootstrap.min.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/spectre.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/spectre-icons.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://shrinefox.com/css/ytv.css&quot; /&gt;
        ///    &lt;link rel=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_head {
            get {
                return ResourceManager.GetString("home_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg version=&quot;1.0&quot; class=&quot;amicitialogo&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;
        /// width=&quot;500.000000pt&quot; height=&quot;500.000000pt&quot; viewBox=&quot;0 0 500.000000 500.000000&quot;
        /// preserveAspectRatio=&quot;xMidYMid meet&quot;&gt;
        ///  &lt;metadata&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;g transform=&quot;translate(0.000000,500.000000) scale(0.100000,-0.100000)&quot;
        ///  fill=&quot;#ffffff&quot; stroke=&quot;none&quot;&gt;
        ///    &lt;path d=&quot;M2256 4489 c-926 -119 -1651 -850 -1766 -1779 -15 -125 -12 -405 5
        ///-529 65 -450 258 -836 579 -1157 67 -66 164 -152 216 -191 136 -100 310 -203
        ///343 -203 14 0 48 114 141 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;!-- EVENT overall_footer_content_after --&gt;
        ///	&lt;/div&gt;
        ///&lt;!-- EVENT overall_footer_page_body_after --&gt;
        ///&lt;/div&gt;
        ///&lt;!--INDEXFOOTER--&gt;
        ///&lt;div id=&quot;darkenwrapper&quot; class=&quot;darkenwrapper&quot; data-ajax-error-title=&quot;{L_AJAX_ERROR_TITLE}&quot; data-ajax-error-text=&quot;{L_AJAX_ERROR_TEXT}&quot; data-ajax-error-text-abort=&quot;{L_AJAX_ERROR_TEXT_ABORT}&quot; data-ajax-error-text-timeout=&quot;{L_AJAX_ERROR_TEXT_TIMEOUT}&quot; data-ajax-error-text-parsererror=&quot;{L_AJAX_ERROR_TEXT_PARSERERROR}&quot;&gt;
        ///    &lt;div id=&quot;darken&quot; class=&quot;darken&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_footer {
            get {
                return ResourceManager.GetString("overall_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE config.html --&gt;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;html dir=&quot;{S_CONTENT_DIRECTION}&quot; lang=&quot;{S_USER_LANG}&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    {META}
        ///    &lt;title&gt;&lt;!-- IF UNREAD_NOTIFICATIONS_COUNT --&gt;({UNREAD_NOTIFICATIONS_COUNT}) &lt;!-- ENDIF --&gt;&lt;!-- IF not S_VIEWTOPIC and not S_VIEWFORUM --&gt;{SITENAME} - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_header {
            get {
                return ResourceManager.GetString("overall_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;column col-4 col-sm-12&quot;&gt;
        ///    &lt;div class=&quot;card&quot;&gt;
        ///        &lt;div class=&quot;card-image&quot;&gt;
        ///            &lt;img class=&quot;img-responsive&quot; src=&quot;POSTMEDIAURL&quot;&gt;
        ///            &lt;div class=&quot;yt-overlay&quot; style=&quot;display:none&quot;&gt;&lt;a href=&quot;EMBEDURL&quot;&gt;&lt;i class=&quot;fas fa-play-circle&quot;&gt;&lt;/i&gt;&lt;/div&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;card-header&quot;&gt;
        ///            &lt;div class=&quot;card-title h5&quot;&gt;
        ///                POSTID POSTTITLE
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;card-subtitle text-muted&quot;&gt;
        ///                GAMEBANANA POSTTYPE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///Theme Name: Justread
        ///Theme URI: https://gretathemes.com/wordpress-themes/justread/
        ///Author: GretaThemes
        ///Author URI: https://gretathemes.com
        ///Description: Justread is a clean and modern WordPress theme that focuses on reading experience. Justread has a grid layout with single column content. The theme uses system fonts and SVG for fast loading. Enjoy reading long content with comfortability.
        ///Version: 1.2.0
        ///License: GNU General Public License v2 or later
        ///License URI: LICENSE
        ///Text Domain: justread
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
